### ISSUE TITLE
Latest version wipes out all instances in the related model instead of those linked by id

### ISSUE THREAD

**Issue by aekevinscroggins** [rocknrolla777/loopback-cascade-delete-mixin#18]
Release 1.2.0 of loopback-cascade-delete-mixin seems to delete all entries in each related model's collection rather than verifying that they are indeed linked via id. After upgrading from 1.1.1 to 1.2.0 and running delete on a base model utilizing this mixin along with deep delete and some related models, virtually the whole database was wiped out. This is a critical issue and I highly recommend reverting to an older version until this is resolved. I'm working on creating a Loopback sandbox to reproduce the issue to assist in diagnosing and fixing this bug. I'm currently using loopback 3.17.1 with mongodb 2.2.33,  loopback-connector-mongodb 3.3.1 and loopback-datasource-juggler 3.14.0.

**Comment by rocknrolla777** [comment]
@aekevinscroggins My apologies!
I've made PR and fixed it! Thanks!

**Comment by aekevinscroggins** [comment]
Awesome! Thank you so much for the quick reply and fix man. I tested it and was able to confirm the issue and that the fix does indeed work! Keep up the awesome work man.
