### ISSUE TITLE
Question(not issue): Relation Context

### ISSUE THREAD

**Issue by thiagovito** [rocknrolla777/loopback-cascade-delete-mixin#4]
Hi @rocknrolla777,

This is more a question than an issue I suppose. The deletion of a cascaded model is working perfectly. However, I do have a Hook rule where I need to read the ID of the item that has been deleted. So I cannot get the where.id of the ctx. When I read the ctx i can see that came from a Parent Model. but I cannot get the Id of the child.

```
MyModel.observe('after delete', function(ctx, next) {
console.log(ctx.where.id)
});
```
Any idea of how to get the child Id in this case?

I appreciate your attention in advance.

**Comment by rocknrolla777** [comment]
Thank you for the issue!  Now I'm working on the new module version and then I'll think about it
